# Generated by Django 2.2.14 on 2020-07-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aulas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aula_nome', models.CharField(max_length=255)),
                ('aula_url', models.CharField(max_length=255)),
                ('pub_dia', models.DateField(verbose_name='date published')),
            ],
        ),
    ]
